### ISSUE TITLE
El feedback de la barra

### ISSUE THREAD

**Issue by DenisaJuarranzBerindea** [Proyectos1-FDI-UCM/c2223-Grupo03#101]
### Descripción
La barra distrae visualmente al jugador del resto del juego. Da la sensación de que tienes que estar todo el rato mirándola para no fallar el "heartbeat". Falta algún tipo de feedback auditivo. 

### Propuesta
Quizás, podríais poner diferentes sonidos al principio y al final de la barra (un "tum" y "tum tum", por ejemplo) para saber cuando comienza y acaba la zona segura. Esto también ayudaría al gamefeel, desde el punto de vista de que, cuando esté lejos de los enemigos, la diferencia entre la sístole y la diástole será mayor que cuando esté cerca de los enemigos, ayudando a crear quizás esa sensación de nerviosismos, peligro y aceleración en los momentos necesarios.

**Comment by Adelpozo04** [comment]
Hemos añadido feedback auditivo para cuando fallas en la barra. Sin embargo consideramos que un segundo sonido al salir de esta podria confundir al jugador y no sería de tanta ayuda.
