### ISSUE TITLE
La luz azul 

### ISSUE THREAD

**Issue by DenisaJuarranzBerindea** [Proyectos1-FDI-UCM/c2223-Grupo03#103]
### Descripción
Parece un feedback de que está ocurriendo algo en esa zona. Como si fuese a aparecer algo, y distrae a la jugabilidad.

### Propuesta
Imagino que será como una forma de hacer ver que fuera hay tormenta. Así que, quizás podría haber un sonido de trueno, para que no pareciese que se acerca una horda de lútanos.

**Comment by AlvaPina** [comment]
Sonido se supone que tiene y de hecho el sonido suena 1s depués de hacer el efecto del rayo como debería ser pero puede que halla fallado algo, lo revisaremos, muchas gracias denisa!
