### ISSUE TITLE
En el nivel tutorial, en la primera sala y hasta que se sale del armario, no se puede pausar el nivel

### ISSUE THREAD

**Issue by DenisaJuarranzBerindea** [Proyectos1-FDI-UCM/c2223-Grupo03#104]
### Descripción
Estando en la primera sala del tutorial, y hasta que no se sale del armario, el juego no se puede pausar. No sé si es un bug, o se espera que esto sea así.

### Pasos
Este error puede reproducirse.
3.	Pulsar P para pausar el juego
4.	Pulsar Resume

**Comment by Adelpozo04** [comment]
es feature
