### ISSUE TITLE
Te conviertes en el sol

### ISSUE THREAD

**Issue by itsJ1mbo** [Proyectos1-FDI-UCM/c2223-Grupo03#106]
### Descripción

En el primer armario del tutorial si sales y entras muchas veces la luz que desprende el
personaje va aumentando

### Pasos 

Detallar los pasos seguidos para poder reproducir el error. Si no se ha podido
reproducir, entonces indicarlo igualmente.
1. Llegar al primer armario del tutorial
2. Entrar y salir del armario repetidas veces

### Captura de pantalla o vídeo
![image](https://user-images.githubusercontent.com/72574312/235319322-58ab114a-5521-42b0-a156-68b127ef2d5c.png)

**Comment by AlvaPina** [comment]
Ostras bien visto! Gracias Jimbo!

**Comment by Adelpozo04** [comment]
Arreglado ese y el de meterse en armarios en la pausa que tambien hemos encontrado.
