### ISSUE TITLE
El sonido de entrada a la barra falla

### ISSUE THREAD

**Issue by LuisEnriqueCabelloBlanco** [Proyectos1-FDI-UCM/c2223-Grupo03#108]
# El sonido de entrada a la barra falla
## Descripción
Al perder la última oportunidad de dar los latidos, el sonido de entrada a la zona segura de la barra se reproduce hasta que termina el evento de quedarse quieto.
Nótese que este bug se ha encontrado en el **primer nivel** cuando el tamaño de la barra se ve alterado pocas veces.
## Pasos

1. Tener un solo golpe.
2. Al principio del recorrido de la barra de heartbeat fallar mientras el corazón se encuentra entrando en la zona segura.

**Comment by Adelpozo04** [comment]
No he podido replicar el bug
