### ISSUE TITLE
Fallo en el evento del primer enemigo (Tutorial)

### ISSUE THREAD

**Issue by LuisEnriqueCabelloBlanco** [Proyectos1-FDI-UCM/c2223-Grupo03#109]
# Fallo en el evento del primer enemigo
## Descripción
Al moverse la **camara** hacia el enemigo el jugador puede seguir moviéndose, si este avanza más allá del armario provoca que el **enemigo desaparezca** y el jugador no pueda avanzar por lo que se sospecha es un muro invisible.
## Pasos

1. Entrar en el pasillo 1
2. Avanzar hacia adelante sin importar el movimiento de cámara
3. Al pasar más allá del armario se verá la situación anteriormente descrita

**Comment by PablooMS** [comment]
Esto está hecho a propósito y la cutscene debería de funcionar una vez vuelves a entrar al armariio

**Comment by Adelpozo04** [comment]
Tal como dice pablo eso es una elección de diseño. Ponemos un muro invisible para forzar al jugador a usar el armario pero sin que haya ningun peligro. Es por ello que el enemigo no aparece hasta que entres dentro, no puedes salir del armario (ahora) hasta que este no se vaya y hay un muro que impide que sigas hasta meterte en él
