### ISSUE TITLE
Lútano rojo no observa a la caja usada por el jugador

### ISSUE THREAD

**Issue by LuisEnriqueCabelloBlanco** [Proyectos1-FDI-UCM/c2223-Grupo03#112]
## Descripción
El lútano no se para delante de la caja del jugador y además pasa a través de ella sin rodearla.
## Pasos

1. Obtener la caja
2. Ubicarse en medio de la patrulla del enemigo

**Comment by PablooMS** [comment]
Al final hemos decidido no hacer que mire a las cajas, ya que es más complicado de lo que esperábamos
