### ISSUE TITLE
No acceder al GameOptions

### ISSUE THREAD

**Issue by SamuelGarciaBazan** [Proyectos1-FDI-UCM/c2223-Grupo03#113]
### Descripción

No se puede volver a acceder al GameOptions del menu principal despues de haber accedido una vez. 

### Pasos 

1. Acceder al gameOptions desde el menu principal
2. Salir dandole al boton de bacjk
3. Intentar volver a acceder al gameOptions (sin cambiar a otro menú antes)

**Comment by PablooMS** [comment]
LLevo intentándolo un rato y no puedo replicar ese bug

**Comment by Adelpozo04** [comment]
El bug ya se arreglo en clase pero como aun no estaba el issue no se cerro
