### ISSUE TITLE
Movimiento diagonal mas rapido

### ISSUE THREAD

**Issue by SamuelGarciaBazan** [Proyectos1-FDI-UCM/c2223-Grupo03#114]
### Descripción

No sabemos si es feature, pero al moverte en diagonal en vez de en solo una direccion el jugador se mueve mas rapido. (nos da la impresion de que tambien sucede con los enemigos)

### Pasos 
1. Moverse en diagonal

**Comment by PablooMS** [comment]
Con los enemigos no sucede porque estos se mueven directamente por sus rutas / hacia el jugador. 
El jugador si que da la impresión de moverse más rápido porque al moverte en dos direcciones a la vez se desplaza más distancia en el mismo tiempo, pero isolando cada uno de los ejes en diagonal, sus velocidades son iguales a moverse respectivamente en ese eje.
