### ISSUE TITLE
Checkpoint de la llave (Prueba del tutorial)

### ISSUE THREAD

**Issue by Paulalemany** [Proyectos1-FDI-UCM/c2223-Grupo03#93]
Cuando coges la llave y mueres el checkpoint no te deja en la sala donde has cogido la llave sino que te deja al principio del nivel. (Sin embargo sí que tienes la llave en tu poder)

Pasos

Avanzar el juego hasta coger la llave
Una vez que tienes la llave en tu poder muere

**Comment by PablooMS** [comment]
Solucionado
