### ISSUE TITLE
Vuelta a la patrulla de los Lútanos verdes (Nivel 3)

### ISSUE THREAD

**Issue by Paulalemany** [Proyectos1-FDI-UCM/c2223-Grupo03#96]
Cuando haces que un enemigo te persigue y vuelve al estado de patrulla no se queda a la misma distancia del otro enemigo como antes sino que van parecidos.	

Pasos
Entrar a la sala de los Lútanos verdes con una caja en nuestro poder
Avanzar por la sala y que uno de los enemigos te persiga
Cuando esté apunto de matarte usar la caja
El enemigo volverá a su estado de patrulla a una distancia diferente del otro enemigo de antes.

Video
https://youtu.be/SWo1cijqmfg

**Comment by PablooMS** [comment]
Eso es un comportamiento esperado ya que los lútanos patrullan independientemente los unos de los otros.
