### ISSUE TITLE
No se encuentra checkpoints en el nivel 1

### ISSUE THREAD

**Issue by DenisaJuarranzBerindea** [Proyectos1-FDI-UCM/c2223-Grupo03#97]
### Descripción
Aún tras haber muerto con todos los enemigos, no hay ningún checkpoint funcional en el nivel 1. 

### Pasos
1. Entrar al nivel 1.
2. Dejarse matar por el primer enemigo - reapareces al inicio del nivel (Es lo esperado)
3. Reiniciar el nivel
4. Dejarse matar por el segundo enemigo - reapareces al inicio del nivel
5. Reiniciar el nivel
6. Dejarse matar por el tercer enemigo, casi al final del nivel - reapareces al inicio del nivel

**Comment by PablooMS** [comment]
Los checkpoints solo se hacen una vez cojas la llave
Además, el checkpoint en el nivel 1 (el cuál ya hemos arreglado y puesto en la posición correspondiente) solo existe para tener una arquitectura de código más sencilla.
