### ISSUE TITLE
Lútanos del Roomba (nivel final)

### ISSUE THREAD

**Issue by Paulalemany** [Proyectos1-FDI-UCM/c2223-Grupo03#98]
Al entrar a la sala del roomba los enemigos estaban bugeados moviéndose freneticamente de arriba a abajo, haciendo así que no sean un problema para el jugador.	

Pasos	
Entrar a la sala de la roomba 
Video
https://youtube.com/shorts/uyNvllDxaD4?feature=share

**Comment by PablooMS** [comment]
Terminado
