### ISSUE TITLE
Lútanos del reloj (nivel final)

### ISSUE THREAD

**Issue by Paulalemany** [Proyectos1-FDI-UCM/c2223-Grupo03#99]
Al usar el reloj con los lútanos verdes y estos vuelven a la patrulla se quedan mirando a una posición distinta a la inicial.

Pasos	
Entrar a la sala de los verdes y coger el reloj
Poner el reloj de forma que atraiga a los enemigos (yo atraje a uno de los dos únicamente)
Dejar que suene el reloj y que el enemigo vuelva a su posición y ruta inicial
El enemigo se queda mirando hacia arriba cuando en un principio estaba mirando hacia abajo
Video
https://youtube.com/shorts/v6ee6zYpHkU?feature=share

**Comment by PablooMS** [comment]
Eso es simplemente como está codificado el giro de los conos de visión. Más que esté mirando hacia arriba o hacia abajo, debería de estar mirando horizontal, pero la velocidad de rotación es demasiado baja

**Comment by PablooMS** [comment]
Aún así, ya está solucionado
